# Generated by Django 2.2 on 2020-05-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='start_date',
        ),
    ]
