# Generated by Django 2.2 on 2020-05-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200524_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
